minio:
  endpoint: http://vod-minio:9000
  access-key: "YOUR_MINIO_ROOT_USER"
  secret-key: "YOUR_MINIO_ROOT_PASSWORD"
  upload-time-limit: 10  # miutes
  download-time-limit: 3 # hours
  buckets:
    raw: raw-video
    hls: hls-video

nginx:
  secure-link-secret: "YOUR_SECURE_LINK_SECRET"

video:
  max-video-size: 2147483648 # 2G
  min-video-size: 0
  allowed-extension: .mp4
  allowed-mime-type: video/mp4

spring:
  datasource:
    url: jdbc:mysql://vod-mysql:3306/video_platform?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "YOUR_ROOT_PASSWORD"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true