name: vod-project
services:
  app:
    container_name: vod-app
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Taipei
    volumes:
      - ..:/workspaces/vod-project:cached
      - maven-repo:/home/vscode/.m2     
    networks:
      - vod-net
    command: ["sleep", "infinity"] 

  db:
    container_name: vod-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "YOUR_ROOT_PASSWORD"
      MYSQL_DATABASE: video_platform
      TZ: Asia/Taipei
    volumes:
      - mysql-data:/var/lib/mysql
      - ../init:/docker-entrypoint-initdb.d
    networks:
      - vod-net

  minio:
    container_name: vod-minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "YOUR_MINIO_ROOT_USER"
      MINIO_ROOT_PASSWORD: "YOUR_MINIO_ROOT_PASSWORD"
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://vod-app:8080/api/video/webhook"
      TZ: Asia/Taipei
    volumes:
      - minio-data:/data
    networks:
      - vod-net
    command: server /data --console-address ":9001"
  createbuckets:
    container_name: vod-createbuckets
    image: minio/mc
    depends_on:
      - minio
    networks:
      - vod-net
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 "YOUR_MINIO_ROOT_USER" "YOUR_MINIO_ROOT_PASSWORD" > /dev/null 2>&1; do 
        sleep 1; 
      done;
      /usr/bin/mc mb --ignore-existing myminio/raw-video;
      /usr/bin/mc mb --ignore-existing myminio/hls-video;
      /usr/bin/mc anonymous set download myminio/hls-video;
      /usr/bin/mc event remove myminio/raw-video arn:minio:sqs::primary:webhook --force || true;
      /usr/bin/mc event add myminio/raw-video arn:minio:sqs::primary:webhook --event put;
      exit 0;
      "
      
networks:
  vod-net:
    name: vod-net
    driver: bridge

volumes:
  maven-repo:
  mysql-data:
  minio-data:
